services:
  # servicio para postgresql 
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: tododb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio para imagen de Spring Boot
  spring-boot:
    build:
      context: ./TodoList
      dockerfile: Dockerfile
    container_name: spring-boot
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:

